---
name: Install Dependencies
description: "Installs required Python packages"
runs:
  using: composite
  steps:
    - run: |
        python3 -m venv env
        source env/bin/activate
        pip install git+https://github.com/davidjkrause/sportsipy@master
        pip3 install -r required_libraries.txt
      shell: bash